respect-gitignore = true
force-exclude = true
exclude = [
    ".venv",
    "__pycache__",
    "venv",
    ".git",
    ".tox",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    "build",
    "dist",
    "*.egg-info",
    "migrations",
    "node_modules",
    "staticfiles",
    "media",
    "logs",
    "temp",
    "tmp",
    "tests/",
    "docs",
    "examples",
    "scripts",
    "tools",
    "config",
    "settings",
    "manage.py",
    "setup.py",
    "pyproject.toml",
    "Makefile",
    "Dockerfile",
    "docker-compose.yml",
    "requirements*.txt",
    "tox.ini",
    "pytest.ini",
    "mypy.ini",
    "ruff.toml",
    "pre-commit-config.yaml",
    ".gitignore",
    "AGENT.md",
    "README.md",
    "LICENSE",
    "LICENSE.md",
    "LICENSE.txt",
    "AUTHORS.md",
    "CHANGELOG.md",
    "CONTRIBUTING.md",
    "SECURITY.md",
    "CODE_OF_CONDUCT.md",
    "py.typed",
]
